### ISSUE TITLE
[feature] 프론트 디자인

### ISSUE THREAD

**Issue by codernoah404** [minzy213/bangphago#3]
- [x]  테마 디테일 페이지 구현
    -> 댓글 기능 오류 수정 필요합니다.
- [x]  사용자 검색 페이지 디자인 수정
- [x]  페이지 라우팅 및 장고와 연결
- [x] #4

**Comment by GitJYoung** [comment]
good

**Comment by codernoah404** [comment]
1. 댓글 리스트 기능에서 한번에 하나의 행만 펼쳐질 수 있도록 기능을 수정해야합니다.
2. 페이지 네이션 기능이 제대로 동작하지 않습니다.

completed

해당 커밋 : [68ad572](https://github.com/minzy213/bangphago/commit/68ad572377294c9d6dd5b85fdb18a82510f0b6ab)

**Comment by codernoah404** [comment]
- [x]  모든 테마의 썸네일이 있는 것이 아님
- 없을 시 " 이미지 준비중 " 으로 대체

- [x]  모든 이미지의 크기가 같지 않음 

- 고정된 크기를 유지 및 썸네일 공간을 꽉 채우게 하는 방법으로 대체

**Comment by codernoah404** [comment]
디테일 화면에서 정보를 가져옵니다.
추후 수정사항
- [ ] 테마 댓글 가져오기 ( 같은 이름의 테마여도 가게가 다르면 id가 다름 )
- [ ] 다른 지점, 같은 테마 구분해줘야함 -> orm 수정
- [ ] 댓글, 테마 출력 페이지에서 버튼 구성해서 다음 페이지 정보 받아와야함
